feat(shell): set errexit, nounset and pipefail
(keep xtrace)

diff --git a/app/configure b/app/configure
--- a/app/configure
+++ b/app/configure
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+# Abort on nonzero exitstatus [-e]
+set -o errexit
+# Abort on unbound variable [-u]
+set -o nounset
+# Don't hide errors within pipes
+set -o pipefail
+
 APP_ID="ox-connector"
 
 if [ "$1" = "install" ] || [ "$1" = "upgrade" ]; then
diff --git a/app/preinst b/app/preinst
--- a/app/preinst
+++ b/app/preinst
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+# Abort on nonzero exitstatus [-e]
+set -o errexit
+# Abort on unbound variable [-u]
+set -o nounset
+# Don't hide errors within pipes
+set -o pipefail
+
 APP_ID="ox-connector"
 
 if [ ! -d "/var/lib/univention-appcenter/apps/$APP_ID/data/secrets/" ]; then
